### ISSUE TITLE
[UI]: Calendar

### ISSUE THREAD

**Issue by JanPoonthong** [JanPoonthong/streaming_schedule#1]
1. **Days of the week**
   1. For example:
      1. Monday
      2. Tuesday
      3. Wednesday
      4. Thursday
      5. Friday
      6. Saturday
      7. Sunday
2. **Times**
   1. The time should be in 15 minutes block
      1. For example:
         1. 15
         2. 30
         3. 45
         4. 60

\* There is a design reference in the attachments

Note: If you do not understand **the task or what to do or how to implement**. You can ask me in [Discord](https://discord.gg/ "‌")

![Design reference](https://github.com/user-attachments/assets/1d1efb2a-ae10-4df6-8e6c-60db14f4337e)

**Comment by emiliebunny** [comment]
May I take this issue?

**Comment by JanPoonthong** [comment]
Yes

**Comment by emiliebunny** [comment]
อยากจะขอตัวอย่าง json data ที่จะใช้เป็น Input ด้วยอะค่ะ
